<?php
/**
 * 17 LĨNH VỰC ĐÁNH GIÁ BẢO MẬT
 * 
 * Danh sách 17 lĩnh vực đánh giá an ninh mạng
 * 
 * @package Config
 */

return [
    [
        'code' => 'IAM',
        'name' => 'Quản lý danh tính và truy cập',
        'name_en' => 'Identity and Access Management',
        'description' => 'Kiểm soát người dùng, xác thực, phân quyền truy cập',
        'weight_percent' => 10,
        'sort_order' => 1,
        'icon' => '🔐',
        'color' => '#3b82f6',
    ],
    [
        'code' => 'NET',
        'name' => 'An ninh mạng',
        'name_en' => 'Network Security',
        'description' => 'Firewall, IDS/IPS, phân đoạn mạng, bảo vệ biên',
        'weight_percent' => 12,
        'sort_order' => 2,
        'icon' => '🌐',
        'color' => '#10b981',
    ],
    [
        'code' => 'SEC',
        'name' => 'Cấu hình bảo mật',
        'name_en' => 'Security Configuration',
        'description' => 'Hardening OS, dịch vụ, ứng dụng, cấu hình an toàn',
        'weight_percent' => 15,
        'sort_order' => 3,
        'icon' => '⚙️',
        'color' => '#8b5cf6',
    ],
    [
        'code' => 'LOG',
        'name' => 'Giám sát và ghi log',
        'name_en' => 'Logging and Monitoring',
        'description' => 'Thu thập, lưu trữ, phân tích log, giám sát sự kiện',
        'weight_percent' => 8,
        'sort_order' => 4,
        'icon' => '📊',
        'color' => '#f59e0b',
    ],
    [
        'code' => 'DATA',
        'name' => 'Bảo vệ dữ liệu',
        'name_en' => 'Data Protection',
        'description' => 'Mã hóa, backup, DLP, bảo vệ dữ liệu nhạy cảm',
        'weight_percent' => 10,
        'sort_order' => 5,
        'icon' => '💾',
        'color' => '#ef4444',
    ],
    [
        'code' => 'APP',
        'name' => 'An ninh ứng dụng',
        'name_en' => 'Application Security',
        'description' => 'OWASP, mã nguồn an toàn, bảo mật API',
        'weight_percent' => 12,
        'sort_order' => 6,
        'icon' => '📱',
        'color' => '#ec4899',
    ],
    [
        'code' => 'END',
        'name' => 'An ninh thiết bị đầu cuối',
        'name_en' => 'Endpoint Security',
        'description' => 'Antivirus, EDR, patch management, bảo vệ endpoint',
        'weight_percent' => 8,
        'sort_order' => 7,
        'icon' => '💻',
        'color' => '#14b8a6',
    ],
    [
        'code' => 'CLOUD',
        'name' => 'An ninh đám mây',
        'name_en' => 'Cloud Security',
        'description' => 'Cấu hình cloud, IAM cloud, bảo vệ workload',
        'weight_percent' => 7,
        'sort_order' => 8,
        'icon' => '☁️',
        'color' => '#06b6d4',
    ],
    [
        'code' => 'DEV',
        'name' => 'DevSecOps',
        'name_en' => 'DevSecOps',
        'description' => 'CI/CD security, scanning pipeline, security as code',
        'weight_percent' => 5,
        'sort_order' => 9,
        'icon' => '🔄',
        'color' => '#a855f7',
    ],
    [
        'code' => 'PHY',
        'name' => 'An ninh vật lý',
        'name_en' => 'Physical Security',
        'description' => 'Server room, access control, camera giám sát',
        'weight_percent' => 3,
        'sort_order' => 10,
        'icon' => '🏢',
        'color' => '#78716c',
    ],
    [
        'code' => 'POL',
        'name' => 'Chính sách và quy trình',
        'name_en' => 'Policy and Procedure',
        'description' => 'Policy, procedure, awareness training, documentation',
        'weight_percent' => 5,
        'sort_order' => 11,
        'icon' => '📋',
        'color' => '#64748b',
    ],
    [
        'code' => 'BCP',
        'name' => 'Khắc phục thảm họa',
        'name_en' => 'Business Continuity',
        'description' => 'DR plan, backup testing, business continuity',
        'weight_percent' => 5,
        'sort_order' => 12,
        'icon' => '🔄',
        'color' => '#f97316',
    ],
    [
        'code' => 'THIRD',
        'name' => 'An ninh bên thứ ba',
        'name_en' => 'Third Party Security',
        'description' => 'Vendor assessment, supply chain, third-party risk',
        'weight_percent' => 3,
        'sort_order' => 13,
        'icon' => '🤝',
        'color' => '#6b7280',
    ],
    [
        'code' => 'MOB',
        'name' => 'An ninh thiết bị di động',
        'name_en' => 'Mobile Security',
        'description' => 'MDM, mobile app security, BYOD policy',
        'weight_percent' => 3,
        'sort_order' => 14,
        'icon' => '📱',
        'color' => '#22c55e',
    ],
    [
        'code' => 'IOT',
        'name' => 'An ninh IoT',
        'name_en' => 'IoT Security',
        'description' => 'Device security, firmware updates, network segmentation',
        'weight_percent' => 2,
        'sort_order' => 15,
        'icon' => '🔌',
        'color' => '#a855f7',
    ],
    [
        'code' => 'AI',
        'name' => 'An ninh AI/ML',
        'name_en' => 'AI/ML Security',
        'description' => 'Model security, data poisoning, adversarial attacks',
        'weight_percent' => 2,
        'sort_order' => 16,
        'icon' => '🤖',
        'color' => '#d946ef',
    ],
    [
        'code' => 'COMP',
        'name' => 'Tuân thủ và pháp lý',
        'name_en' => 'Compliance and Legal',
        'description' => 'GDPR, ISO 27001, PCI-DSS, legal requirements',
        'weight_percent' => 5,
        'sort_order' => 17,
        'icon' => '⚖️',
        'color' => '#6366f1',
    ],
];